NER_CLINICAL_LABELS = {"Medication", "History", "Sign_symptom", "Lab_value", "Diagnosis"}

CLINICAL_SYNONYMS = {
    "hypotension":    "Sign_symptom",
    "septic shock":   "Sign_symptom",
    "chest pain":     "Sign_symptom",
    "wheezing":       "Sign_symptom",
    "tachycardia":    "Sign_symptom",
    "dyspnea":        "Sign_symptom",
    "lisinopril":     "Medication",
    "amlodipine":     "Medication",
    "metformin":      "Medication",
    "salbutamol":     "Medication",
    "norepinephrine": "Medication",
    "meropenem":      "Medication",
    "warfarin":       "Medication",
    "insulin":        "Medication",
}

MEDICAL_LATIN = {
    "pro re nata":   "as needed",
    "per oral":      "by mouth",
    "bis in die":    "twice daily",
    "ter in die":    "three times daily",
    "quater in die": "four times daily",
    "omne nocte":    "every night",
    "ante cibum":    "before meals",
    "post cibum":    "after meals",
    "statim":        "immediately",
    "ad libitum":    "as desired",
}

GROUND_TRUTH = {
    "N001": {
        "Medication":   ["metformin", "lisinopril"],
        "History":      ["hypertension", "type 2 diabetes"],
        "Sign_symptom": ["fatigue", "chest pain"],
    },
    "N002": {
        "Medication":   ["norepinephrine", "meropenem"],
        "Sign_symptom": ["septic shock", "hypotension"],
        "Lab_value":    ["80/50"],
    },
    "N003": {
        "Medication":   ["salbutamol"],
        "Sign_symptom": ["wheezing", "shortness of breath"],
        "Lab_value":    ["320"],
    },
}

KNOWLEDGE_BASE = [
    "Metformin: first-line type 2 diabetes treatment. Side effects: nausea, lactic acidosis, B12 deficiency. Contraindicated in eGFR <30.",
    "Lisinopril: ACE inhibitor for hypertension and heart failure. Side effects: dry cough, hyperkalemia, angioedema. Monitor renal function.",
    "Norepinephrine: vasopressor of choice in septic shock. Target MAP >65 mmHg. Monitor for digital ischemia.",
    "Meropenem: carbapenem antibiotic for gram-negative sepsis. Dose adjust in renal impairment. Risk of seizures at high doses.",
    "Salbutamol (albuterol): short-acting beta-2 agonist for acute asthma. Side effects: tachycardia, hypokalemia, tremor.",
    "Septic shock: sepsis + vasopressor requirement + lactate >2 mmol/L. Mortality 30-40%. Early antibiotics within 1 hour critical.",
    "Hypertension: BP >140/90 mmHg. First-line: ACE inhibitors, ARBs, CCBs, thiazides. Target <130/80 in high-risk patients.",
    "Type 2 diabetes: HbA1c target <7% for most patients. Monitor for microvascular and macrovascular complications.",
    "Asthma: FEV1/FVC <0.7. Peak flow <80% personal best indicates poor control. Stepwise management per GINA guidelines.",
    "ICD-10 E11: Type 2 diabetes. ICD-10 I10: Essential hypertension. ICD-10 J45: Asthma. ICD-10 A41: Sepsis.",
    "Gram-negative bacteremia: blood culture mandatory. Empiric carbapenem therapy. De-escalate based on sensitivity results.",
    "Peak flow <50% personal best: severe exacerbation, requires emergency treatment. 50-80%: moderate, increase bronchodilator.",
    "Chest pain in diabetic patients: silent MI risk. Obtain ECG, troponin, CXR. Do not delay workup.",
    "Hyperkalemia with ACE inhibitors: monitor K+ especially with NSAIDs, potassium-sparing diuretics, or renal impairment.",
    "Lactic acidosis with metformin: rare but life-threatening. Hold metformin perioperatively and if eGFR drops acutely.",
    "Septic shock bundles: blood cultures before antibiotics, 30ml/kg IV crystalloid, vasopressors if MAP <65, lactate monitoring.",
    "B12 deficiency from metformin: check levels annually. Supplement if symptomatic neuropathy or levels <200 pg/mL.",
    "ARDS: PaO2/FiO2 <300 on PEEP >5. Lung-protective ventilation: TV 6ml/kg IBW, plateau pressure <30 cmH2O.",
    "Carbapenem resistance: contact ID for colistin, tigecycline, or ceftazidime-avibactam. Strict infection control measures.",
    "ACE inhibitor angioedema: immediate epinephrine 0.3mg IM, antihistamines, corticosteroids. Airway management priority.",
    "Bisoprolol: beta-1 selective blocker for heart failure and hypertension. Do not abruptly discontinue.",
    "Ramipril: ACE inhibitor with cardiovascular protective effect post-MI. Monitor BP, renal function, potassium.",
    "Azithromycin: macrolide antibiotic for community-acquired pneumonia. Risk of QT prolongation.",
    "Vasopressin: second-line vasopressor in septic shock refractory to norepinephrine. Fixed dose 0.03 units/min.",
    "Amlodipine: calcium channel blocker for hypertension. Side effects: peripheral edema, flushing. Safe in renal impairment.",
    "Dialysis in AKI: indicated for refractory fluid overload, hyperkalemia, acidosis, or uremia.",
    "Procalcitonin: biomarker for bacterial infection and sepsis. Trend down indicates antibiotic response.",
    "Anticoagulation post-orthopedic surgery: LMWH or DOACs for DVT/PE prophylaxis. Duration 10-35 days.",
    "Community-acquired pneumonia severity: PSI or CURB-65 score guides inpatient vs outpatient management.",
    "Oxygen saturation target: 94-98% in most patients. 88-92% in COPD to avoid hypercapnia.",
    "Warfarin: anticoagulant for AF and DVT. Monitor INR target 2-3. Many drug and food interactions.",
    "Insulin glargine: long-acting basal insulin for type 1 and type 2 diabetes. Monitor for hypoglycemia.",
    "Furosemide: loop diuretic for fluid overload and heart failure. Monitor electrolytes and renal function.",
    "Vancomycin: glycopeptide antibiotic for MRSA. Monitor trough levels and renal function closely.",
    "Dexamethasone: corticosteroid used in severe COVID-19, ARDS, and meningitis. Monitor blood glucose.",
]
SYNTHETIC_DATA = {
    "Discharge / General Ward": [
        "Patient discharged after 3-day admission for community-acquired pneumonia. Completed azithromycin course. SpO2 97% on room air.",
        "Post-appendectomy discharge. Wound clean and dry. Prescribed amoxicillin-clavulanate 625mg TID for 5 days.",
        "Patient with type 2 diabetes discharged after glycemic optimization. HbA1c improved to 7.1%. Continue insulin glargine 20 units nightly.",
        "Discharge following elective cholecystectomy. Tolerating oral diet. Prescribed paracetamol and ibuprofen for pain.",
        "Patient recovered from acute gastroenteritis. Rehydrated and tolerating oral fluids. Discharged with ORS and loperamide.",
        "Post-total knee replacement discharge. Physiotherapy initiated. Anticoagulation with rivaroxaban 10mg for 14 days.",
        "Patient discharged after treatment for cellulitis left leg. Completed IV cefazolin, transitioned to oral cefalexin.",
        "Hypertensive urgency resolved. BP 138/88 on amlodipine 10mg. Discharged with outpatient follow-up in 1 week.",
        "Patient with atrial fibrillation discharged on warfarin. INR 2.4. Cardiology follow-up in 2 weeks.",
        "Post-TURP discharge. Catheter removed. Voiding well. Prescribed tamsulosin 0.4mg once daily.",
        "Discharge after management of acute gout. Uric acid 9.2 mg/dL. Started allopurinol 100mg. NSAIDs for acute phase.",
        "Patient with COPD exacerbation discharged after 4 days. Completed prednisolone and salbutamol nebulization course.",
        "Post-cesarean section discharge day 3. Wound healing well. Prescribed iron supplementation and folic acid.",
        "Patient discharged after DVT treatment. Started rivaroxaban 15mg BID for 21 days then 20mg OD.",
        "Discharge summary post-thyroidectomy. Calcium levels stable. Prescribed levothyroxine 100mcg daily.",
        "Patient with liver cirrhosis Child-Pugh B discharged. Ascites controlled. Continue spironolactone and furosemide.",
        "Post-cardiac catheterization discharge. No complications. Dual antiplatelet therapy with aspirin and clopidogrel.",
        "Patient discharged after syncope workup. Echo and Holter normal. No structural heart disease identified.",
        "Discharge following laparoscopic hernia repair. Minimal pain. Resume normal activities in 2 weeks.",
        "Patient with epilepsy discharged after breakthrough seizure. Valproate dose increased to 1000mg BD.",
        "Post-fracture fixation discharge. Non-weight bearing for 6 weeks. Calcium and vitamin D supplementation.",
        "Patient discharged after acute pancreatitis. Lipase normalized. Resume oral diet gradually. Avoid alcohol.",
        "Discharge after treatment of urinary tract infection. Completed nitrofurantoin course. Urine culture cleared.",
        "Patient with hypothyroidism discharged. TSH normalized on levothyroxine 75mcg. Follow up in 3 months.",
        "Post-ERCP discharge. No complications. Continue ursodeoxycholic acid for gallstone prevention.",
        "Patient discharged after management of iron deficiency anemia. Hemoglobin 10.2g/dL. Oral iron supplementation.",
        "Discharge following rhinoplasty. Wound care instructions given. Follow-up with ENT in 1 week.",
        "Patient with schizophrenia discharged after acute psychotic episode. Olanzapine 10mg daily. Psychiatry follow-up.",
        "Post-tonsillectomy discharge. Soft diet for 2 weeks. Analgesia with paracetamol and ibuprofen.",
        "Patient discharged after hypoglycemic episode. Insulin dose adjusted. Glucose monitoring education reinforced.",
        "Discharge after management of acute migraine. Sumatriptan effective. Prescribed topiramate for prophylaxis.",
        "Patient with rheumatoid arthritis discharged. Methotrexate dose optimized. Monitor LFTs monthly.",
        "Post-cataract surgery discharge. Eye drops prescribed. Review ophthalmology in 1 week.",
        "Patient discharged after management of septic arthritis right knee. Joint aspiration done. IV antibiotics completed.",
        "Discharge following coronary artery bypass grafting. Sternum healing well. Cardiac rehab referral made.",
        "Patient with Crohn's disease discharged. Azathioprine and mesalazine continued. GI follow-up in 4 weeks.",
        "Post-laparotomy discharge. Bowel sounds present. Wound intact. Dietary advice given.",
        "Patient discharged after dengue fever management. Platelet count 150,000. Avoid NSAIDs.",
        "Discharge following treatment of hyperkalemia. Potassium 4.1 mEq/L. Dietary counseling provided.",
        "Patient with heart failure NYHA class II discharged. Ejection fraction 40%. Continue bisoprolol and furosemide.",
        "Post-herniorrhaphy discharge. No signs of infection. Light activities for 4 weeks.",
        "Patient discharged after management of acute exacerbation asthma. Peak flow 85% personal best. Continue ICS/LABA.",
        "Discharge after cholecystitis management. Cholecystectomy planned electively. Low-fat diet advised.",
        "Patient with psoriasis discharged. Methotrexate 15mg weekly initiated. Sun protection advised.",
        "Post-circumcision discharge. Wound healing well. Prescribed topical antibiotic ointment.",
        "Patient discharged after management of hyponatremia. Sodium 136 mEq/L. Fluid restriction continued.",
        "Discharge following tympanoplasty. Ear packing removed. Audiogram in 6 weeks.",
        "Patient with lupus nephritis discharged. Mycophenolate and hydroxychloroquine continued. Renal function stable.",
        "Post-parathyroidectomy discharge. Calcium supplemented. Monitor serum calcium weekly.",
        "Patient discharged after management of acute liver failure. Encephalopathy resolved. Lactulose continued.",
    ],
    "ICU / Critical Care": [
        "ICU day 2. Patient with ARDS on mechanical ventilation. FiO2 60%, PEEP 12 cmH2O. Prone positioning initiated.",
        "Post-cardiac arrest ICU admission. ROSC achieved after 15 minutes. Targeted temperature management at 36C.",
        "Patient with status epilepticus. Midazolam infusion ongoing. EEG monitoring initiated. Neurology consulted.",
        "ICU admission for acute liver failure. INR 3.2. N-acetylcysteine infusion started. Liver transplant team alerted.",
        "Severe traumatic brain injury GCS 6. Intubated. ICP monitoring in situ. Mannitol 20% administered.",
        "ICU day 4. Septic shock with multi-organ failure. Renal replacement therapy initiated. Procalcitonin 45 ng/mL.",
        "Patient with massive pulmonary embolism. Thrombolysis with alteplase administered. Hemodynamics improving.",
        "ICU admission for diabetic ketoacidosis. pH 7.1, glucose 480 mg/dL. Insulin infusion and fluid resuscitation.",
        "Patient with hypertensive emergency. BP 230/140 mmHg. Labetalol IV infusion initiated. CT head: no bleed.",
        "ICU day 1. Burn patient 40% TBSA. Fluid resuscitation per Parkland formula. Intubated for airway protection.",
        "Post-operative ICU admission following AAA repair. Hemodynamically stable on vasopressor support.",
        "Patient with acute MI complicated by cardiogenic shock. IABP inserted. Emergency PCI performed.",
        "ICU admission for severe community-acquired pneumonia. BiPAP initiated. Procalcitonin 12 ng/mL.",
        "Patient with necrotizing fasciitis. Emergency surgical debridement done. IV meropenem and clindamycin.",
        "ICU day 3. Post-neurosurgery. Intracranial pressure controlled. Sedation weaning attempted.",
        "Severe anaphylaxis following penicillin administration. Epinephrine IM given. Intubated for airway edema.",
        "ICU admission for acute pancreatitis with APACHE II score 18. NPO. Aggressive IV fluid resuscitation.",
        "Patient with tension pneumothorax. Needle decompression followed by chest tube insertion. SpO2 improved.",
        "ICU day 5. VAP suspected. Bronchoalveolar lavage sent. Antibiotic escalated to piperacillin-tazobactam.",
        "Patient with thyroid storm. Heart rate 158 bpm. Propylthiouracil, propranolol, and dexamethasone started.",
        "Post-liver transplant ICU day 1. Tacrolimus initiated. LFTs trending down. Bile output adequate.",
        "ICU admission for heat stroke. Core temperature 41.2C. Active cooling initiated. Rhabdomyolysis present.",
        "Patient with severe sepsis from urinary source. Lactate 4.2 mmol/L. Central line inserted. Broad-spectrum antibiotics.",
        "ICU day 2. ECMO initiated for refractory cardiogenic shock. Anticoagulation with heparin infusion.",
        "Patient with toxic megacolon. Emergency colectomy performed. Post-operative ICU monitoring.",
        "ICU admission for subarachnoid hemorrhage Hunt-Hess grade 3. Nimodipine started. Neurosurgery reviewing.",
        "Patient with acute kidney injury requiring dialysis. Potassium 6.8 mEq/L. Emergency hemodialysis initiated.",
        "Post-esophagectomy ICU day 1. Epidural analgesia in situ. Nasojejunal feeds commenced.",
        "ICU day 6. Ventilator weaning in progress. Spontaneous breathing trial failed. Tracheostomy planned.",
        "Patient with severe asthma attack. PaCO2 55 mmHg. Intubated. Magnesium sulfate and aminophylline given.",
        "ICU admission for overdose with tricyclic antidepressant. QRS 160ms. Sodium bicarbonate infusion.",
        "Post-pneumonectomy ICU day 1. Mediastinal shift monitored. Chest drain output 200ml/hr.",
        "Patient with meningococcal septicemia. Purpuric rash. Ceftriaxone IV started. Dexamethasone given.",
        "ICU day 3. Hemodynamic instability post-trauma. Massive transfusion protocol activated.",
        "Patient with acute respiratory failure secondary to COVID-19. Dexamethasone and remdesivir started.",
        "ICU admission for malignant hyperthermia post-anesthesia. Dantrolene administered. Core temp 40.8C.",
        "Post-cardiac surgery ICU day 1. Pacing wires in situ. Chest drain draining serosanguinous fluid.",
        "Patient with hepatic encephalopathy grade 3. Lactulose and rifaximin. Ammonia 180 micromol/L.",
        "ICU day 4. Refractory hypoxemia. Sildenafil added for pulmonary hypertension. RV function monitoring.",
        "Patient with severe hypothermia core temp 28C. Warmed IV fluids. External warming blankets applied.",
        "ICU admission for aortic dissection type A. Emergency surgical repair performed. Post-op hemodynamically stable.",
        "Patient with acute stroke GCS 10. Thrombolysis given within 3-hour window. CT perfusion: large penumbra.",
        "ICU day 2. Abdominal compartment syndrome. Bladder pressure 28 mmHg. Surgical decompression planned.",
        "Post-bone marrow transplant ICU admission. Neutropenic sepsis. Empiric antifungal added.",
        "Patient with severe preeclampsia. BP 170/110. MgSO4 infusion. Emergency cesarean planned.",
        "ICU day 5. Weaning from vasopressors. Norepinephrine reduced to 0.05 mcg/kg/min. MAP 68 mmHg.",
        "Patient with rabies encephalitis. Supportive care only. Family counseled on prognosis.",
        "ICU admission for acute hemolytic transfusion reaction. Transfusion stopped. Hydration and monitoring.",
        "Post-CABG ICU day 2. Atrial fibrillation new onset. Amiodarone IV initiated. Rate controlled.",
        "Patient with severe hypovolemic shock post-trauma. Damage control surgery completed. ICU monitoring.",
    ],
    "Outpatient": [
        "Follow-up for type 2 diabetes. HbA1c 7.8%. Metformin dose increased to 1000mg BD. Lifestyle counseling.",
        "Routine hypertension review. BP 142/88 mmHg. Amlodipine 5mg added to current regimen.",
        "Asthma management review. Symptoms well controlled. Continue fluticasone/salmeterol inhaler. Peak flow 420 L/min.",
        "Outpatient psychiatry review. Depression in remission. Continue sertraline 50mg. Next appointment in 8 weeks.",
        "Cardiology clinic follow-up post-MI. Echo EF 55%. Continue dual antiplatelet and statin therapy.",
        "Rheumatology review for rheumatoid arthritis. DAS28 score 2.8. Methotrexate effective. Continue current dose.",
        "Nephrology clinic. CKD stage 3b. eGFR 38 ml/min. BP 128/78. Restrict protein intake. Avoid NSAIDs.",
        "Neurology outpatient for epilepsy. Seizure-free for 12 months. Consider medication reduction in 6 months.",
        "Endocrinology follow-up for hypothyroidism. TSH 2.1 mIU/L. Levothyroxine dose adequate. Review in 6 months.",
        "Outpatient oncology review. Patient on chemotherapy cycle 3. Tolerating well. Neutrophil count adequate.",
        "Pulmonology clinic for COPD. FEV1 58% predicted. Increase tiotropium. Pulmonary rehab referral.",
        "Dermatology review for eczema. SCORAD 18. Topical tacrolimus effective. Emollient continued.",
        "Gastroenterology follow-up for IBD. Calprotectin 80 ug/g. Crohn's in remission. Continue azathioprine.",
        "Urology outpatient for BPH. IPSS score 12. PSA 2.8 ng/mL. Continue tamsulosin. Cystoscopy planned.",
        "Ophthalmology review for diabetic retinopathy. No progression. HbA1c target reinforced.",
        "Outpatient for antenatal care 28 weeks. BP 118/72. FHR 148 bpm. GDM screen negative.",
        "Orthopedic clinic post-fracture. X-ray shows good callus formation. Progress weight bearing.",
        "Follow-up for atrial fibrillation. Heart rate 72 bpm. INR 2.6. Continue warfarin. Cardiology review.",
        "Allergy clinic for allergic rhinitis. Skin prick test positive house dust mite. Immunotherapy discussed.",
        "HIV clinic follow-up. CD4 count 620. Viral load undetectable. Continue ART. No side effects.",
        "Outpatient for chronic migraine. Frequency reduced on topiramate 50mg BD. Continue and review in 3 months.",
        "Hepatology clinic for chronic hepatitis B. HBV DNA 1200 IU/mL. Tenofovir initiated.",
        "Endocrinology for Graves disease. FT4 normalizing on carbimazole. TRAb levels declining.",
        "Outpatient follow-up post-pulmonary embolism. Rivaroxaban continued for 6 months total. D-dimer 0.3.",
        "Geriatric outpatient assessment. Patient 82 years. Mild cognitive impairment. Fall risk moderate. Physiotherapy.",
        "Fertility clinic consultation. Day 3 FSH 8 mIU/mL. AMH 2.1 ng/mL. IVF discussed as option.",
        "Pediatric outpatient for asthma. 8-year-old. Montelukast added. Trigger avoidance counseling given.",
        "Outpatient for chronic back pain. MRI: L4-L5 disc herniation. Physiotherapy and NSAIDs prescribed.",
        "Nutrition clinic for obesity. BMI 34. Caloric restriction and exercise plan. Orlistat considered.",
        "Wound care clinic. Diabetic foot ulcer grade 2. Dressing changed. Blood glucose poorly controlled.",
        "Follow-up for systemic lupus erythematosus. SLEDAI score 4. Hydroxychloroquine and prednisolone continued.",
        "Outpatient ENT for chronic sinusitis. CT: mucosal thickening. Nasal corticosteroid spray prescribed.",
        "Cardiology outpatient for heart failure. BNP 380 pg/mL. Furosemide dose increased. Fluid restriction.",
        "Diabetology clinic. Type 1 DM review. Continuous glucose monitoring data reviewed. Insulin ratio adjusted.",
        "Outpatient for sleep apnea. AHI 22 on CPAP. Compliance good. Next review in 6 months.",
        "Hematology clinic for chronic ITP. Platelet count 45,000. Eltrombopag dose maintained.",
        "Psychiatry outpatient for bipolar disorder. Mood stable on lithium. Level 0.8 mEq/L. Continue.",
        "Podiatry clinic for diabetic neuropathy. Foot care education reinforced. Custom orthotics fitted.",
        "Follow-up for chronic kidney disease. Hemoglobin 10.2 g/dL. Erythropoietin started.",
        "Outpatient for Parkinson disease. Levodopa dose adjusted. Good motor response. Physiotherapy ongoing.",
        "Immunology clinic for primary immunodeficiency. IVIG infusion administered. IgG level adequate.",
        "Oncology follow-up post-chemotherapy. CA-125 normalizing. CT scan: no residual disease.",
        "Outpatient for osteoporosis. DEXA T-score -2.8. Alendronate 70mg weekly and calcium started.",
        "Cardiology review for stable angina. Exercise stress test negative. Medical management continued.",
        "Follow-up for chronic obstructive jaundice. Bilirubin 3.2 mg/dL. ERCP scheduled.",
        "Outpatient for childhood obesity. BMI 28. Nutritional counseling. Screen for metabolic syndrome.",
        "Neurology review for multiple sclerosis. No new lesions on MRI. Interferon beta continued.",
        "Outpatient for recurrent UTI. MSU culture: E. coli. Prophylactic nitrofurantoin 50mg nightly.",
        "Antenatal 36 weeks. Fetal position cephalic. Group B strep swab sent. Birth plan discussed.",
        "Outpatient for essential tremor. Propranolol 40mg BD effective. No functional limitation.",
    ],
}
